# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-17 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190617_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='is_del',
            field=models.BooleanField(default=False),
        ),
    ]
