# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-17 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_goods_is_del'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='change_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='create_time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
