# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-17 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190617_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='g_name',
            field=models.CharField(db_column='name', default='', max_length=255),
        ),
    ]
