# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-17 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190617_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='g_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
