# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-17 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190617_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='g_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
