# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-17 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190617_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='img',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
