# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-17 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_goods_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='img',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
