# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-19 09:40
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190619_0906'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='goods',
            managers=[
                ('goodsObjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
